-- ============================================================================
-- Aminos MX — datos iniciales (categorías, 24 productos, lotes, cupón)
-- Generado desde js/main.js
-- ============================================================================

insert into public.categories (id, name_es, name_en, icon, sort_order) values
  ('perdida-peso', 'Pérdida de peso', 'Weight loss', 'i-trending-down', 1),
  ('recomposicion', 'Recomposición corporal', 'Body recomposition', 'i-zap', 2),
  ('metabolicos', 'Metabólicos', 'Metabolic', 'i-heart-pulse', 3),
  ('regenerativos', 'Regenerativos', 'Regenerative', 'i-syringe', 4),
  ('anti-edad', 'Anti-edad', 'Anti-aging', 'i-sparkles', 5),
  ('aminoacidos', 'Aminoácidos', 'Amino acids', 'i-flame', 6)
on conflict (id) do nothing;

insert into public.products
  (slug, sku, name, category_id, presentation_es, presentation_en, purity,
   price_cents, compare_at_cents, desc_es, desc_en, tags_es, tags_en,
   stock, bestseller, is_new, status, sort_order) values
  ('semaglutide-5', 'SEMAGLUTIDE-5', 'Semaglutide', 'perdida-peso',
   'Vial liofilizado 5 mg', 'Lyophilized vial 5 mg', '≥99%',
   189000, 229000,
   'Análogo GLP-1 estudiado en investigación sobre control de apetito, sensación de saciedad y manejo de peso. Incluye certificado de análisis (COA) por lote.', 'GLP-1 analog studied in research on appetite control, satiety and weight management. Includes a certificate of analysis (COA) per batch.',
   array['GLP-1','Saciedad','Control de apetito'], array['GLP-1','Satiety','Appetite control'],
   34, true, false, 'active', 1),
  ('tirzepatide-10', 'TIRZEPATIDE-10', 'Tirzepatide', 'perdida-peso',
   'Vial liofilizado 10 mg', 'Lyophilized vial 10 mg', '≥99%',
   249000, 299000,
   'Agonista dual GIP/GLP-1 de referencia en estudios de reducción de peso y salud metabólica. Liofilizado con pureza verificada por HPLC.', 'Dual GIP/GLP-1 agonist, a reference in weight-reduction and metabolic-health studies. Lyophilized with HPLC-verified purity.',
   array['GIP/GLP-1','Pérdida de peso','Metabolismo'], array['GIP/GLP-1','Weight loss','Metabolism'],
   27, true, false, 'active', 2),
  ('retatrutide-10', 'RETATRUTIDE-10', 'Retatrutide', 'perdida-peso',
   'Vial liofilizado 10 mg', 'Lyophilized vial 10 mg', '≥99%',
   329000, null,
   'Agonista triple GIP/GLP-1/Glucagón. Compuesto de nueva generación en investigación metabólica y de composición corporal.', 'Triple GIP/GLP-1/Glucagon agonist. A next-generation compound in metabolic and body-composition research.',
   array['Triple agonista','Nueva generación'], array['Triple agonist','Next generation'],
   15, false, true, 'active', 3),
  ('cagrilintide-5', 'CAGRILINTIDE-5', 'Cagrilintide', 'perdida-peso',
   'Vial liofilizado 5 mg', 'Lyophilized vial 5 mg', '≥99%',
   289000, null,
   'Análogo de amilina estudiado en combinación con GLP-1 para investigación de saciedad y control glucémico.', 'Amylin analog studied in combination with GLP-1 for satiety and glycemic-control research.',
   array['Amilina','Saciedad'], array['Amylin','Satiety'],
   12, false, false, 'active', 4),
  ('aod9604-5', 'AOD9604-5', 'AOD-9604', 'perdida-peso',
   'Vial liofilizado 5 mg', 'Lyophilized vial 5 mg', '≥99%',
   149000, 179000,
   'Fragmento modificado de hGH estudiado en investigación de lipólisis y metabolismo de grasas sin efecto en IGF-1.', 'Modified hGH fragment studied in lipolysis and fat-metabolism research without an effect on IGF-1.',
   array['Lipólisis','Metabolismo de grasas'], array['Lipolysis','Fat metabolism'],
   41, false, false, 'active', 5),
  ('ipamorelin-5', 'IPAMORELIN-5', 'Ipamorelin', 'recomposicion',
   'Vial liofilizado 5 mg', 'Lyophilized vial 5 mg', '≥99%',
   139000, 169000,
   'Secretagogo de GH altamente selectivo. Referencia en estudios de masa magra, recuperación y calidad del sueño.', 'Highly selective GH secretagogue. A reference in lean-mass, recovery and sleep-quality studies.',
   array['GHRP','Masa magra','Recuperación'], array['GHRP','Lean mass','Recovery'],
   48, true, false, 'active', 6),
  ('cjc1295-nodac-5', 'CJC1295-NODAC-5', 'CJC-1295 sin DAC', 'recomposicion',
   'Vial liofilizado 5 mg', 'Lyophilized vial 5 mg', '≥99%',
   149000, null,
   'GHRH modificado de vida media corta. Se estudia comúnmente en sinergia con Ipamorelin para pulsos naturales de GH.', 'Modified short-half-life GHRH. Commonly studied in synergy with Ipamorelin for natural GH pulses.',
   array['GHRH','Sinergia con Ipamorelin'], array['GHRH','Ipamorelin synergy'],
   39, false, false, 'active', 7),
  ('tesamorelin-5', 'TESAMORELIN-5', 'Tesamorelin', 'recomposicion',
   'Vial liofilizado 5 mg', 'Lyophilized vial 5 mg', '≥99%',
   279000, null,
   'GHRH estudiado en investigación sobre grasa visceral, cognición y composición corporal.', 'GHRH studied in research on visceral fat, cognition and body composition.',
   array['GHRH','Grasa visceral'], array['GHRH','Visceral fat'],
   9, false, true, 'active', 8),
  ('mk677-10', 'MK677-10', 'MK-677 (Ibutamoren)', 'recomposicion',
   'Vial liofilizado 10 mg', 'Lyophilized vial 10 mg', '≥99%',
   159000, 189000,
   'Secretagogo oral de GH estudiado en investigación de densidad ósea, masa magra y sueño profundo.', 'Oral GH secretagogue studied in research on bone density, lean mass and deep sleep.',
   array['Secretagogo','Densidad ósea'], array['Secretagogue','Bone density'],
   52, false, false, 'active', 9),
  ('igf1lr3-1', 'IGF1LR3-1', 'IGF-1 LR3', 'recomposicion',
   'Vial liofilizado 1 mg', 'Lyophilized vial 1 mg', '≥99%',
   319000, null,
   'Análogo de IGF-1 de vida media prolongada. Referencia en estudios de hipertrofia e hiperplasia muscular.', 'Long-half-life IGF-1 analog. A reference in muscle hypertrophy and hyperplasia studies.',
   array['IGF-1','Hipertrofia'], array['IGF-1','Hypertrophy'],
   7, false, false, 'active', 10),
  ('motsc-10', 'MOTSC-10', 'MOTS-c', 'metabolicos',
   'Vial liofilizado 10 mg', 'Lyophilized vial 10 mg', '≥99%',
   189000, 219000,
   'Péptido mitocondrial estudiado en investigación de sensibilidad a la insulina, ejercicio y envejecimiento metabólico.', 'Mitochondrial peptide studied in research on insulin sensitivity, exercise and metabolic aging.',
   array['Mitocondrial','Sensibilidad insulínica'], array['Mitochondrial','Insulin sensitivity'],
   23, true, false, 'active', 11),
  ('5amino1mq-50', '5AMINO1MQ-50', '5-Amino-1MQ', 'metabolicos',
   'Vial liofilizado 50 mg', 'Lyophilized vial 50 mg', '≥99%',
   169000, null,
   'Inhibidor de NNMT estudiado en investigación de metabolismo celular, energía y composición corporal.', 'NNMT inhibitor studied in research on cellular metabolism, energy and body composition.',
   array['NNMT','Energía celular'], array['NNMT','Cellular energy'],
   31, false, false, 'active', 12),
  ('aicar-50', 'AICAR-50', 'AICAR', 'metabolicos',
   'Vial liofilizado 50 mg', 'Lyophilized vial 50 mg', '≥99%',
   199000, null,
   'Activador de AMPK de referencia en estudios de resistencia metabólica y metabolismo energético.', 'AMPK activator, a reference in metabolic-endurance and energy-metabolism studies.',
   array['AMPK','Resistencia metabólica'], array['AMPK','Metabolic endurance'],
   18, false, false, 'active', 13),
  ('bpc157-5', 'BPC157-5', 'BPC-157', 'regenerativos',
   'Vial liofilizado 5 mg', 'Lyophilized vial 5 mg', '≥99%',
   129000, 159000,
   'Péptido de protección corporal derivado de proteína gástrica. El más estudiado en investigación de reparación de tejidos, tendones y mucosa gastrointestinal.', 'Body-protection peptide derived from gastric protein. The most studied in research on tissue, tendon and gastrointestinal-mucosa repair.',
   array['Reparación','Tejidos','GI'], array['Repair','Tissues','GI'],
   64, true, false, 'active', 14),
  ('tb500-5', 'TB500-5', 'TB-500', 'regenerativos',
   'Vial liofilizado 5 mg', 'Lyophilized vial 5 mg', '≥99%',
   139000, null,
   'Fragmento de Timosina Beta-4 estudiado en investigación de cicatrización, flexibilidad y recuperación muscular.', 'Thymosin Beta-4 fragment studied in research on wound healing, flexibility and muscle recovery.',
   array['Tβ4','Cicatrización','Flexibilidad'], array['Tβ4','Healing','Flexibility'],
   57, true, false, 'active', 15),
  ('ghkcu-50', 'GHKCU-50', 'GHK-Cu', 'regenerativos',
   'Vial liofilizado 50 mg', 'Lyophilized vial 50 mg', '≥99%',
   159000, 189000,
   'Tripéptido de cobre estudiado en investigación de colágeno, piel, cabello y procesos de remodelación tisular.', 'Copper tripeptide studied in research on collagen, skin, hair and tissue-remodeling processes.',
   array['Colágeno','Piel','Cobre'], array['Collagen','Skin','Copper'],
   44, true, false, 'active', 16),
  ('kpv-10', 'KPV-10', 'KPV', 'regenerativos',
   'Vial liofilizado 10 mg', 'Lyophilized vial 10 mg', '≥99%',
   149000, null,
   'Tripéptido derivado de α-MSH estudiado en investigación de inflamación intestinal y procesos inmunomoduladores.', 'α-MSH-derived tripeptide studied in research on intestinal inflammation and immunomodulatory processes.',
   array['Antiinflamatorio','Inmunomodulador'], array['Anti-inflammatory','Immunomodulator'],
   26, false, false, 'active', 17),
  ('wolverine-blend', 'WOLVERINE-BLEND', 'Blend BPC-157 + TB-500', 'regenerativos',
   'Vial liofilizado 5 mg + 5 mg', 'Lyophilized vial 5 mg + 5 mg', '≥99%',
   239000, 268000,
   'Combinación “Wolverine” de los dos péptidos regenerativos más estudiados, en un solo vial liofilizado.', '“Wolverine” combination of the two most-studied regenerative peptides in a single lyophilized vial.',
   array['Combo','Recuperación avanzada'], array['Combo','Advanced recovery'],
   21, false, true, 'active', 18),
  ('epitalon-10', 'EPITALON-10', 'Epitalon', 'anti-edad',
   'Vial liofilizado 10 mg', 'Lyophilized vial 10 mg', '≥99%',
   169000, null,
   'Tetrapéptido estudiado en investigación de telomerasa, ritmos circadianos y biogerontología.', 'Tetrapeptide studied in research on telomerase, circadian rhythms and biogerontology.',
   array['Telomerasa','Longevidad'], array['Telomerase','Longevity'],
   19, false, false, 'active', 19),
  ('nad500', 'NAD500', 'NAD+', 'anti-edad',
   'Vial liofilizado 500 mg', 'Lyophilized vial 500 mg', '≥99%',
   189000, 229000,
   'Coenzima esencial estudiada en investigación de energía mitocondrial, sirtuinas y salud celular.', 'Essential coenzyme studied in research on mitochondrial energy, sirtuins and cellular health.',
   array['Coenzima','Mitocondria','Energía'], array['Coenzyme','Mitochondria','Energy'],
   33, true, false, 'active', 20),
  ('thymalin-20', 'THYMALIN-20', 'Thymalin', 'anti-edad',
   'Vial liofilizado 20 mg', 'Lyophilized vial 20 mg', '≥99%',
   179000, null,
   'Complejo timótico estudiado en investigación de inmunorregulación y envejecimiento del sistema inmune.', 'Thymic complex studied in research on immunoregulation and immune-system aging.',
   array['Inmunidad','Timo'], array['Immunity','Thymus'],
   14, false, false, 'active', 21),
  ('lcarnitina-500', 'LCARNITINA-500', 'L-Carnitina', 'aminoacidos',
   'Frasco 500 mg/mL × 10 mL', 'Bottle 500 mg/mL × 10 mL', 'Grado USP',
   69000, 89000,
   'Aminoácido esencial en el transporte de ácidos grasos a la mitocondria. Formato inyectable de grado USP.', 'Essential amino acid in the transport of fatty acids to the mitochondria. USP-grade injectable format.',
   array['Metabolismo de grasas','Energía'], array['Fat metabolism','Energy'],
   70, false, false, 'active', 22),
  ('glutamina-200', 'GLUTAMINA-200', 'L-Glutamina', 'aminoacidos',
   'Frasco 200 mg/mL × 30 mL', 'Bottle 200 mg/mL × 30 mL', 'Grado USP',
   59000, null,
   'El aminoácido más abundante del organismo. Apoyo en recuperación muscular y salud intestinal.', 'The most abundant amino acid in the body. Support for muscle recovery and gut health.',
   array['Recuperación','Intestino'], array['Recovery','Gut'],
   82, false, false, 'active', 23),
  ('bcaa-blend', 'BCAA-BLEND', 'BCAA 2:1:1', 'aminoacidos',
   'Frasco × 30 mL', 'Bottle × 30 mL', 'Grado USP',
   79000, 95000,
   'Leucina, isoleucina y valina en proporción 2:1:1. Base de suplementación para síntesis proteica.', 'Leucine, isoleucine and valine in a 2:1:1 ratio. A supplementation base for protein synthesis.',
   array['Síntesis proteica','Base'], array['Protein synthesis','Base'],
   55, false, false, 'active', 24)
on conflict (slug) do nothing;

insert into public.batches
  (code, product_id, purity_hplc, identity_ms, endotoxins, residual_water,
   lyophilized_on, lab, published)
select v.code, p.id, v.purity, v.ms, v.endo, '< 3.0 %',
       current_date - 60, 'Laboratorio independiente (USA)', true
from (values
  ('AMX-2608', 'bpc157-5', 99.42, '1419.5 Da', '< 0.5 EU/mg'),
  ('AMX-2611', 'tb500-5', 99.1, '4963.4 Da', '< 0.5 EU/mg'),
  ('AMX-2617', 'ipamorelin-5', 99.6, '711.9 Da', '< 0.5 EU/mg'),
  ('AMX-2624', 'ghkcu-50', 99.2, '340.8 Da', '< 0.5 EU/mg'),
  ('AMX-2630', 'nad500', 99.8, '663.4 Da', '< 0.5 EU/mg'),
  ('AMX-2634', 'semaglutide-5', 99.3, '4113.6 Da', '< 0.5 EU/mg')
) as v(code, slug, purity, ms, endo)
join public.products p on p.slug = v.slug
on conflict (code) do nothing;

insert into public.coupons (code, kind, value, min_subtotal_cents, active) values
  ('BULK10', 'percent', 10, 500000, true),
  ('BIENVENIDA', 'percent', 5, 0, true)
on conflict (code) do nothing;
